version: '3'
services:
  my-redis:
    image: redis
    ports:
      - '16379:6379'
    volumes:
    - '~/.m2:/maven'

  my-mongodb:
    image: mongo
    ports:
      - '17017:27017'

  my-zookeeper:
    image: zookeeper
    ports:
      - '12181:2181'